# These are the default stages.
image: maven:3.6.3-openjdk-11
before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - build
  - test
  - deploy

build:
  stage: test
  script:
    - echo "Maven build started"
    - mvn verify

deploy:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
