apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carstore
  template:
    metadata:
      labels:
        app: carstore
    spec:
      containers:
      - name: carstore
        image: carstore:0.0.1
        ports:
        - containerPort: 8080
