version: '3.3' #https://www.digitalocean.com/community/tutorials/containerizing-a-node-js-application-for-development-with-docker-compose

services:
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    restart: unless-stopped
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_ROOT_PASSWORD: nm116421M
      MYSQL_DATABASE: carstore
      MYSQL_USER: root
      MYSQL_PASSWORD: nm116421M
    ports:
      - "80:8080"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nm116421M
      MYSQL_DATABASE: carstore
      MYSQL_USER: root
      MYSQL_PASSWORD: nm116421M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
